# Generated by Django 3.1.3 on 2020-12-13 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materialprofiles', '0003_auto_20201213_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdescription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialdescriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
