# Generated by Django 3.1.3 on 2020-12-10 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expired_at',
            field=models.DateField(default=datetime.datetime(2020, 12, 17, 9, 19, 33, 182657)),
        ),
    ]
