# Generated by Django 3.1.3 on 2020-12-13 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201211_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expired_at',
            field=models.DateField(default=datetime.datetime(2020, 12, 20, 15, 55, 39, 351278)),
        ),
    ]
